### ISSUE TITLE
sonobuoy retrieve is frequently crashing for k8s-conformance-test-suite.sh

### ISSUE THREAD

**Issue by mtulio** [Azure/azure-arc-validation#48]
## Description of problem:

`sonobuoy retrieve` sometimes is returning the `error retrieving results: unexpected EOF` when running the platform k8s conformance tests, so the artifact is not downloaded and the script will not run successfully even if the conformance tests have passed.

## Version-Release number of selected component (if applicable):

- [aak8sSupportPolicy.txt](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/aak8sSupportPolicy.txt)

```
1.5.2
1.4.0
1.3.8
```

- sonobuoy
```
$ sonobuoy version
Sonobuoy Version: v0.56.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 0665cd322b11bb40c2774776de765c38d8104bed
```

## How reproducible:

Frequently. It seems to be related to the size of the artifact

## Steps to Reproduce:
1. Run the k8s conformance test script: `bash -x k8s-conformance-test-suite.sh`
2. Check the line running `sonobuoy retrieve`, if it returns an error, the artifact name will not be filled into var and `sonobuoy results $sonobuoyResults` will fail

## Actual results:

```
18:33:28 Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
+ echo 'Test execution completed..Retrieving results'
Test execution completed..Retrieving results
++ sonobuoy retrieve
error retrieving results: unexpected EOF
+ sonobuoyResults=
+ sonobuoy results
Error: accepts 1 arg(s), received 0
Usage:
  sonobuoy results archive.tar.gz [flags]

Flags:
  -h, --help            help for results
  -m, --mode string     Modifies the format of the output. Valid options are report, detailed, or dump. (default "report")
  -n, --node string     Traverse results starting at the node with the given name. Defaults to the real root.
  -p, --plugin string   Which plugin to show results for. Defaults to printing them all.
  -s, --skip-prefix     When printing items linking to files, only print the file contents.

Global Flags:
      --level level   Log level. One of {panic, fatal, error, warn, info, debug, trace} (default info)

ERRO[0000] accepts 1 arg(s), received 0        
```

## Expected results:

1. `sonobuoy retrieve` downloads successfully the artifacts
2. `k8s-conformance-test-suite.sh` handle the error from retrieving collecting the artifacts direct from the pod

## Additional info:

I can work around it copying the artifact from `/tmp` directory of the `sonobuoy` pod.

**Comment by anraghun** [comment]
Closing this as we've refactored the test harness to a containerized one which auto retrieves the test results. We haven't seen this issue repro recently.
