### ISSUE TITLE
k8s-conformance-test is missing securityContext for pod kube-aad-proxy, container fluent-bit

### ISSUE THREAD

**Issue by mtulio** [Azure/azure-arc-validation#49]
## Description of problem:

The container `fluent-bit` for a pod `kube-aad-proxy` is trying to bind on a privileged port which is not allowed by default on OpenShift.

## Version-Release number of selected component (if applicable):

- Kubernetes distribution:

```
- Upstream Kubernetes Version: v1.22.3+e790d7f
- K8s Distribution Version: OpenShift Container Platform 4.9.17
```

- [arc-k8s-platform/platform.yaml](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/arc-k8s-platform/platform.yaml)

```
arck8sconformance.azurecr.io/arck8sconformance/clusterconnect:0.1.5
```

- [aak8sSupportPolicy.txt](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/aak8sSupportPolicy.txt)

```
1.5.2
1.4.0
1.3.8
```

- sonobuoy
```
$ sonobuoy version
Sonobuoy Version: v0.56.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 0665cd322b11bb40c2774776de765c38d8104bed
```

## How reproducible:

Always

## Steps to Reproduce:
1. Run the k8s conformance test script: `bash -x k8s-conformance-test-suite.sh`
2. Check the logs of container `fluent-bit` for pod `kube-aad-proxy ` on namespace `azure-arc`

## Actual results:

```
time="2022-02-21T19:19:22Z" level=fatal msg="Failed to create server. Error:failed to create listener: failed to listen on 0.0.0.0:443: listen tcp 0.0.0.0:443: bind: permission denied"
```

## Expected results:

- The container does not bind in the privileged ports (>1024)

Desired:
- The container does not need to run as privileged

## Additional info:

When patching the deployment adding correct `securityContext` to this pod when the conformance-test is running I can work around the issue:
```
kuebctl patch deployment.apps/kube-aad-proxy -n azure-arc \
    --type='json' \
    -p='[{"op": "replace", "path": "/spec/template/spec/containers/1/securityContext", "value":{"privileged": true, "runAsGroup": 0,"runAsUser": 0}}]'
```

**Comment by anraghun** [comment]
This is the expected behavior as of now. Earlier, we expected the customers/partners to associate a privileged scc to the service account used by kube aad proxy prior to Arc onboarding but this task has since been added to the onboarding command itself. The pre-requisite on customers/partners has been removed.
