### ISSUE TITLE
k8s-conformance-test is leaking client_secret on artifacts

### ISSUE THREAD

**Issue by mtulio** [Azure/azure-arc-validation#51]
## Description of problem:

The `$AZ_CLIENT_SECRET` exported from script is being saved on collected artifacts even after running the cleaner python script.

The python script is missing to clean two files (changed to `REDACTED`):

```
 $ jq -r '.Definition.podSpec.containers[].env[] | select (.name == "CLIENT_SECRET")' testResult-1.5.2/plugins/azure-arc-platform/defintion.json  
{
  "name": "CLIENT_SECRET",
  "value": "REDACTED"
}
$ jq -r '.["plugin-1.yaml"]' testResult-1.5.2/resources/ns/sonobuoy/core_v1_configmaps.json |grep CLIENT_SECRET -A1
    - name: CLIENT_SECRET
      value:     - name: CLUSTER_NAME
--
  - name: CLIENT_SECRET
    value: "REDACTED"
```

## Version-Release number of selected component (if applicable):

- Kubernetes distribution:

```
- Upstream Kubernetes Version: v1.22.3+e790d7f
- K8s Distribution Version: OpenShift Container Platform 4.9.17
```

- [arc-k8s-platform/platform.yaml](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/arc-k8s-platform/platform.yaml)

```
arck8sconformance.azurecr.io/arck8sconformance/clusterconnect:0.1.5
```

- [aak8sSupportPolicy.txt](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/aak8sSupportPolicy.txt)

```
1.5.2
1.4.0
1.3.8
```

- sonobuoy
```
$ sonobuoy version
Sonobuoy Version: v0.56.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 0665cd322b11bb40c2774776de765c38d8104bed
```

## How reproducible:

Always

## Steps to Reproduce:
1. Run the k8s conformance test script: `bash -x k8s-conformance-test-suite.sh`
2. Wait to tests finished and artifact is retrieved and script to clean runs
3. Extract artifacts
4. Lookup for Client secret environment (exported by script) into the artifact: ` grep -rni $AZ_CLIENT_SECRET artifact_path/` 

## Actual results:

The files still have sensitive information:
- testResult-1.5.2/plugins/azure-arc-platform/defintion.json
- testResult-1.5.2/resources/ns/sonobuoy/core_v1_configmaps.json

## Expected results:

No credentials are saved on artifacts that will be published to a shared storage

**Comment by anraghun** [comment]
This has been fixed
