### ISSUE TITLE
k8s-conformance-test need to decrease default Security Context Constraint policies on OpenShift to run successfully

### ISSUE THREAD

**Issue by mtulio** [Azure/azure-arc-validation#52]
## Description of problem:

When running the k8s-conformance-tests on OpenShift we need to decrease default SCC policies to make the tests schedule and run. When troubleshooting we can see a lot of pods with privileged secutirytContexts being scheduled on `azure-arc` namespace.

So to make the jobs run correctly we needed to run those modifications:

- allow all services accounts to run as privileged SCC (it could be more specific for NS or SA, but we have no visibility of what SA is used by the jobs)

```
oc adm policy add-scc-to-group privileged system:authenticated system:serviceaccounts
oc adm policy add-scc-to-group anyuid system:authenticated system:serviceaccounts
```

> Note: I tried to run allow only the serviceAccount `sonobuoy-serviceaccount` (defined [here](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/arc-k8s-platform/platform.yaml#L7)) but did not work.

We perceived that the pods scheduled on `azure-arc` namespace need two constraints to be enabled (which is already allowed on `restricted` policy:
```
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
```

## Version-Release number of selected component (if applicable):

- Kubernetes distribution:

```
- Upstream Kubernetes Version: v1.22.3+e790d7f
- K8s Distribution Version: OpenShift Container Platform 4.9.17
```

- [arc-k8s-platform/platform.yaml](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/arc-k8s-platform/platform.yaml)

```
arck8sconformance.azurecr.io/arck8sconformance/clusterconnect:0.1.5
```

- [aak8sSupportPolicy.txt](https://github.com/Azure/azure-arc-validation/blob/a78b9a1126ef4c2eab3a21769e150a46f829735a/testsuite/aak8sSupportPolicy.txt)

```
1.5.2
1.4.0
1.3.8
```

- sonobuoy
```
$ sonobuoy version
Sonobuoy Version: v0.56.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 0665cd322b11bb40c2774776de765c38d8104bed
```

## How reproducible:

Always

## Steps to Reproduce:
1. Run the k8s conformance test script: `bash -x k8s-conformance-test-suite.sh`
2. Observe the logs of plugin jobs/pods in `sonobuoy` namespace, and deployments in `azure-arc` namespace

## Actual results:

When allowing serviceAccounts to run as privileged, the jobs will run successfully:
```
oc adm policy add-scc-to-group privileged system:authenticated system:serviceaccounts
oc adm policy add-scc-to-group anyuid system:authenticated system:serviceaccounts
```

## Expected results:

No need to allow serviceAccounts to run as privileged context.

## Additional info:

Researching about sonobuoy requirements for a custom plugin, I can see that it does not require by default plugins to run as privileged. So I am assuming that the elevated privileges are being added by custom plugins that is created and new resources created by its plugins.

Look at the example of a custom plugin I've tested:

- Create the sample plugin

```
$ sonobuoy gen plugin \
  --name=hello-world \
  --image schnake/easy-sonobuoy-cmds:v0.1 \
  --arg="echo hello world" > hello-world.yaml
```

- Check the pod spec without escalating privileges by default: `$ cat hello-world.yaml `
```yaml
sonobuoy-config:
  driver: Job
  plugin-name: hello-world
  result-format: raw
spec:
  args:
  - echo hello world
  command:
  - ./run.sh
  image: schnake/easy-sonobuoy-cmds:v0.1
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

```

- Run it
```
$ sonobuoy run --plugin hello-world.yaml --dns-namespace="" --dns-pod-labels="" --wait
(...)

0:56:58         PLUGIN     NODE     STATUS   RESULT   PROGRESS
10:56:58    hello-world   global   complete   passed           
10:56:58 
10:56:58 Sonobuoy plugins have completed. Preparing results for download.
(...)
10:59:58 Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```
- Get the results
```
$ res_file=$(sonobuoy retrieve) && \
  mkdir results && tar -xf $res_file -C results &&
  cat results/plugins/hello-world/sonobuoy_results.yaml
```
```yaml
name: hello-world
status: passed
meta:
  type: summary
items:
- name: out0
  status: passed
  meta:
    file: results/global/out0
```

**Comment by anraghun** [comment]
@mtulio This is not a trait of the conformance tests but the nature of Arc enabled K8s. We are dabbling with introducing a "least-privileged" mode for Arc K8s which will reduce the permissions our service accounts take to exactly what's needed. But this would come at the cost of ease of onboarding, upgrades and usage.
