### ISSUE TITLE
Result upload failed exec the pod for result fecthing

### ISSUE THREAD

**Issue by fabianofranz** [Azure/azure-arc-validation#70]
All three Arc versions runs (N, N-1, and N-3) finish successfully with the `passed` status, but right after the last `Buffer wait 5 minutes...` message I get the error below in the `azure-arc-kubernetes-conformance-nnnnn` pod logs.

 ```
...
...

Namespace "sonobuoy" has been deleted

Deleted all ClusterRoles and ClusterRoleBindings.
Buffer wait 5 minutes...
Result upload failed exec the pod for result fecthing
```

After which the pod is still in the `Running` state but apparently paused with no more log messages being added. 

When that happens, the .tar.gz results are present on the pod and I can `kubectl cp` them successfully. Checking the blob storage I could confirm they were automatically uploaded there. So despite the message, apparently there were no loss in the ability of the validation to finish successfully.

I saw that in all 6 validation runs I did in a row with different versions of OpenShift (4.9, 4.10, 4.11).

**Comment by fabianofranz** [comment]
FYI @v-vgujjula

**Comment by anraghun** [comment]
Thanks @fabianofranz, this is a bug in the test harness. As you pointed out, the results have uploaded. Adding @v-suvbera to take a look at the bug.

**Comment by v-suvabera** [comment]
As mentioned, closing this ticket.
