### ISSUE TITLE
No support for multiple versions of a partner offering on the blob directory structure

### ISSUE THREAD

**Issue by fabianofranz** [Azure/azure-arc-validation#71]
I'd like to run the the Arc validation on three versions of our partner offering (OpenShift), meaning at the moment versions 4.11.latest, 4.10.latest, and 4.9.latest. 

The blob storage creates separate directories for each 3 tested versions of Arc (_conformance-results-major-1-minor-7-patch-4_, _conformance-results-major-1-minor-6-patch-16_, and _conformance-results-major-1-minor-5-patch-2_ as of now) but makes no distinction of the partner offering versions specified in the `partner-metadata.md` file when naming the files and directories in the blob structure.

That leads to .tar.gz results files being overridden after consecutive runs, even if they're related to different partner offering versions (it's always called `conformance-results-openshift.tar.gz`). 

I'd suggest to sanitize the value in the `Upstream Kubernetes Version` metadata and use that as a suffix to the results filenames.

**Comment by fabianofranz** [comment]
FYI @v-vgujjula

**Comment by anraghun** [comment]
@fabianofranz the [`offering-name`](https://github.com/Azure/azure-arc-validation/blob/main/testsuite/azure-arc-conformance.properties#L8) parameter will allow you to differentiate between the 3 OpenShift versions. You can set them as openshift-4.11, openshift-4.10 etc.

**Comment by fabianofranz** [comment]
@anraghun ack, that makes sense. Thank you!
